_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 41
                - 49
                - 51
                - 55
            "2":
                - 1
                - 41
                - 49
                - 51
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.11
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
batch_size:
    value: 64
device:
    value: cpu
epochs:
    value: 8
learning_rate:
    value: 0.0003
lr_decay:
    value: 0.9
vocab_size:
    value: 13
weight_decay:
    value: 0.1
